apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: rolandsankara/reverseproxy
        name: reverseproxy
        imagePullPolicy: Always
        resources:
          requests:
            memory: "50Mi"
          limits:
            memory: "100Mi"
        args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
        ports:
        - containerPort: 8080
      restartPolicy: Always
